# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: actuated.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='actuated.proto',
  package='',
  serialized_pb=_b('\n\x0e\x61\x63tuated.proto\"3\n\x17_targetPowerStateParams\x12\x18\n\x10targetPowerState\x18\x01 \x02(\x08\"F\n\x1a_targetControlPolicyParams\x12(\n\x13targetControlPolicy\x18\x01 \x02(\x0e\x32\x0b.ctrlPolicy\";\n\x1a_targetManualControlParams\x12\x1d\n\x15targetBrightnessLevel\x18\x01 \x01(\r\"E\n\x16_targetAutoTimerParams\x12\x14\n\x0ctargetOnTime\x18\x01 \x01(\r\x12\x15\n\rtargetOffTime\x18\x02 \x01(\r\"A\n\x14_targetAutoLuxParams\x12\x13\n\x0btargetOnLux\x18\x01 \x01(\r\x12\x14\n\x0ctargetOffLux\x18\x02 \x01(\r\"\xb6\x02\n\x14targetConfigurations\x12\x32\n\x10targetPowerState\x18\x01 \x01(\x0b\x32\x18._targetPowerStateParams\x12>\n\x19targetControlPolicyParams\x18\x02 \x01(\x0b\x32\x1b._targetControlPolicyParams\x12\x36\n\x15targetAutoTimerParams\x18\x03 \x01(\x0b\x32\x17._targetAutoTimerParams\x12\x32\n\x13targetAutoLuxParams\x18\x04 \x01(\x0b\x32\x15._targetAutoLuxParams\x12>\n\x19targetManualControlParams\x18\x05 \x01(\x0b\x32\x1b._targetManualControlParams*6\n\nctrlPolicy\x12\x0c\n\x08\x41UTO_LUX\x10\x00\x12\x0e\n\nAUTO_TIMER\x10\x01\x12\n\n\x06MANUAL\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_CTRLPOLICY = _descriptor.EnumDescriptor(
  name='ctrlPolicy',
  full_name='ctrlPolicy',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AUTO_LUX', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUTO_TIMER', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MANUAL', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=655,
  serialized_end=709,
)
_sym_db.RegisterEnumDescriptor(_CTRLPOLICY)

ctrlPolicy = enum_type_wrapper.EnumTypeWrapper(_CTRLPOLICY)
AUTO_LUX = 0
AUTO_TIMER = 1
MANUAL = 2



__TARGETPOWERSTATEPARAMS = _descriptor.Descriptor(
  name='_targetPowerStateParams',
  full_name='_targetPowerStateParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='targetPowerState', full_name='_targetPowerStateParams.targetPowerState', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=69,
)


__TARGETCONTROLPOLICYPARAMS = _descriptor.Descriptor(
  name='_targetControlPolicyParams',
  full_name='_targetControlPolicyParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='targetControlPolicy', full_name='_targetControlPolicyParams.targetControlPolicy', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=141,
)


__TARGETMANUALCONTROLPARAMS = _descriptor.Descriptor(
  name='_targetManualControlParams',
  full_name='_targetManualControlParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='targetBrightnessLevel', full_name='_targetManualControlParams.targetBrightnessLevel', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=202,
)


__TARGETAUTOTIMERPARAMS = _descriptor.Descriptor(
  name='_targetAutoTimerParams',
  full_name='_targetAutoTimerParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='targetOnTime', full_name='_targetAutoTimerParams.targetOnTime', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='targetOffTime', full_name='_targetAutoTimerParams.targetOffTime', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=273,
)


__TARGETAUTOLUXPARAMS = _descriptor.Descriptor(
  name='_targetAutoLuxParams',
  full_name='_targetAutoLuxParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='targetOnLux', full_name='_targetAutoLuxParams.targetOnLux', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='targetOffLux', full_name='_targetAutoLuxParams.targetOffLux', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=340,
)


_TARGETCONFIGURATIONS = _descriptor.Descriptor(
  name='targetConfigurations',
  full_name='targetConfigurations',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='targetPowerState', full_name='targetConfigurations.targetPowerState', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='targetControlPolicyParams', full_name='targetConfigurations.targetControlPolicyParams', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='targetAutoTimerParams', full_name='targetConfigurations.targetAutoTimerParams', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='targetAutoLuxParams', full_name='targetConfigurations.targetAutoLuxParams', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='targetManualControlParams', full_name='targetConfigurations.targetManualControlParams', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=343,
  serialized_end=653,
)

__TARGETCONTROLPOLICYPARAMS.fields_by_name['targetControlPolicy'].enum_type = _CTRLPOLICY
_TARGETCONFIGURATIONS.fields_by_name['targetPowerState'].message_type = __TARGETPOWERSTATEPARAMS
_TARGETCONFIGURATIONS.fields_by_name['targetControlPolicyParams'].message_type = __TARGETCONTROLPOLICYPARAMS
_TARGETCONFIGURATIONS.fields_by_name['targetAutoTimerParams'].message_type = __TARGETAUTOTIMERPARAMS
_TARGETCONFIGURATIONS.fields_by_name['targetAutoLuxParams'].message_type = __TARGETAUTOLUXPARAMS
_TARGETCONFIGURATIONS.fields_by_name['targetManualControlParams'].message_type = __TARGETMANUALCONTROLPARAMS
DESCRIPTOR.message_types_by_name['_targetPowerStateParams'] = __TARGETPOWERSTATEPARAMS
DESCRIPTOR.message_types_by_name['_targetControlPolicyParams'] = __TARGETCONTROLPOLICYPARAMS
DESCRIPTOR.message_types_by_name['_targetManualControlParams'] = __TARGETMANUALCONTROLPARAMS
DESCRIPTOR.message_types_by_name['_targetAutoTimerParams'] = __TARGETAUTOTIMERPARAMS
DESCRIPTOR.message_types_by_name['_targetAutoLuxParams'] = __TARGETAUTOLUXPARAMS
DESCRIPTOR.message_types_by_name['targetConfigurations'] = _TARGETCONFIGURATIONS
DESCRIPTOR.enum_types_by_name['ctrlPolicy'] = _CTRLPOLICY

_targetPowerStateParams = _reflection.GeneratedProtocolMessageType('_targetPowerStateParams', (_message.Message,), dict(
  DESCRIPTOR = __TARGETPOWERSTATEPARAMS,
  __module__ = 'actuated_pb2'
  # @@protoc_insertion_point(class_scope:_targetPowerStateParams)
  ))
_sym_db.RegisterMessage(_targetPowerStateParams)

_targetControlPolicyParams = _reflection.GeneratedProtocolMessageType('_targetControlPolicyParams', (_message.Message,), dict(
  DESCRIPTOR = __TARGETCONTROLPOLICYPARAMS,
  __module__ = 'actuated_pb2'
  # @@protoc_insertion_point(class_scope:_targetControlPolicyParams)
  ))
_sym_db.RegisterMessage(_targetControlPolicyParams)

_targetManualControlParams = _reflection.GeneratedProtocolMessageType('_targetManualControlParams', (_message.Message,), dict(
  DESCRIPTOR = __TARGETMANUALCONTROLPARAMS,
  __module__ = 'actuated_pb2'
  # @@protoc_insertion_point(class_scope:_targetManualControlParams)
  ))
_sym_db.RegisterMessage(_targetManualControlParams)

_targetAutoTimerParams = _reflection.GeneratedProtocolMessageType('_targetAutoTimerParams', (_message.Message,), dict(
  DESCRIPTOR = __TARGETAUTOTIMERPARAMS,
  __module__ = 'actuated_pb2'
  # @@protoc_insertion_point(class_scope:_targetAutoTimerParams)
  ))
_sym_db.RegisterMessage(_targetAutoTimerParams)

_targetAutoLuxParams = _reflection.GeneratedProtocolMessageType('_targetAutoLuxParams', (_message.Message,), dict(
  DESCRIPTOR = __TARGETAUTOLUXPARAMS,
  __module__ = 'actuated_pb2'
  # @@protoc_insertion_point(class_scope:_targetAutoLuxParams)
  ))
_sym_db.RegisterMessage(_targetAutoLuxParams)

targetConfigurations = _reflection.GeneratedProtocolMessageType('targetConfigurations', (_message.Message,), dict(
  DESCRIPTOR = _TARGETCONFIGURATIONS,
  __module__ = 'actuated_pb2'
  # @@protoc_insertion_point(class_scope:targetConfigurations)
  ))
_sym_db.RegisterMessage(targetConfigurations)


# @@protoc_insertion_point(module_scope)
